import { Injectable } from '@angular/core';
import { Game } from '../models/game.model';

@Injectable({ providedIn: 'root' })
export class GamesService {
  private dummy_games = [
    {
      id: 'g1',
      name: 'Catan',
      shortDescription: 'Iconic economic game about settlers building their colonies.',
      numberOfPlayers: '3-4',
      playingTime: '60-90 min',
      minAge: 10,
      weight: 2.3,
      designer: 'Klaus Teuber',
      artist: 'Volkan Baga',
      comment: 'Świetna dla początkujących graczy, klasyk gatunku.',
    },
    {
      id: 'g2',
      name: 'Carcassonne',
      shortDescription: 'Building medieval cities and roads with tiles.',
      numberOfPlayers: '2-5',
      playingTime: '30-45 min',
      minAge: 7,
      weight: 1.9,
      designer: 'Klaus-Jürgen Wrede',
      artist: 'Doris Matthäus',
      comment: 'Losowość kafelków daje dużo regrywalności.',
    },
    {
      id: 'g3',
      name: 'Ticket to Ride',
      shortDescription: 'Building railway routes across the world map.',
      numberOfPlayers: '2-5',
      playingTime: '45-60 min',
      minAge: 8,
      weight: 1.8,
      designer: 'Alan R. Moon',
      artist: 'Julien Delval',
      comment: 'Łatwa do nauczenia, ale z fajną strategią.',
    },
    {
      id: 'g4',
      name: '7 Wonders',
      shortDescription: 'Develop your civilization through three ages.',
      numberOfPlayers: '3-7',
      playingTime: '30 min',
      minAge: 10,
      weight: 2.3,
      designer: 'Antoine Bauza',
      artist: 'Miguel Coimbra',
      comment: 'Świetna w dużej grupie, szybka i dynamiczna.',
    },
    {
      id: 'g5',
      name: 'Splendor',
      shortDescription: 'Collecting gems and developing Renaissance merchants.',
      numberOfPlayers: '2-4',
      playingTime: '30 min',
      minAge: 10,
      weight: 1.8,
      designer: 'Marc André',
      artist: 'Pascal Quidault',
      comment: 'Idealna gra wprowadzająca w planszówki.',
    },
    {
      id: 'g6',
      name: 'Dominion',
      shortDescription: 'Deck-building game where you create your own card deck.',
      numberOfPlayers: '2-4',
      playingTime: '30 min',
      minAge: 13,
      weight: 2.4,
      designer: 'Donald X. Vaccarino',
      artist: 'Matthias Catrein',
      comment: 'Pierwowzór gier typu deck-building.',
    },
    {
      id: 'g7',
      name: 'Pandemic',
      shortDescription: 'Cooperative fight against spreading diseases.',
      numberOfPlayers: '2-4',
      playingTime: '45 min',
      minAge: 8,
      weight: 2.4,
      designer: 'Matt Leacock',
      artist: 'Josh Cappel',
      comment: 'Wciągająca gra kooperacyjna o ratowaniu świata.',
    },
    {
      id: 'g8',
      name: 'Azul',
      shortDescription: 'Laying colorful tiles in a Portuguese palace.',
      numberOfPlayers: '2-4',
      playingTime: '30-45 min',
      minAge: 8,
      weight: 1.9,
      designer: 'Michael Kiesling',
      artist: 'Chris Quilliams',
      comment: 'Prosta zasady, ale dużo głębi w wyborach.',
    },
    {
      id: 'g9',
      name: 'Scythe',
      shortDescription: 'Alternate 1920s Europe with mechs and factions.',
      numberOfPlayers: '1-7',
      playingTime: '90-120 min',
      minAge: 14,
      weight: 3.4,
      designer: 'Jamey Stegmaier',
      artist: 'Jakub Różalski',
      comment: 'Piękna gra strategiczna z unikalnym klimatem.',
    },
    {
      id: 'g10',
      name: 'Terraforming Mars',
      shortDescription: 'Corporations cooperate (and compete) in terraforming Mars.',
      numberOfPlayers: '1-5',
      playingTime: '120 min',
      minAge: 12,
      weight: 3.3,
      designer: 'Jacob Fryxelius',
      artist: 'Isaac Fryxelius',
      comment: 'Ogromna regrywalność i klimat naukowy.',
    },
    {
      id: 'g11',
      name: 'Wingspan',
      shortDescription: 'Collecting birds in a nature reserve.',
      numberOfPlayers: '1-5',
      playingTime: '40-70 min',
      minAge: 10,
      weight: 2.4,
      designer: 'Elizabeth Hargrave',
      artist: 'Beth Sobel',
      comment: 'Piękne ilustracje i przyjemna mechanika.',
    },
    {
      id: 'g12',
      name: 'Gloomhaven',
      shortDescription: 'Epic fantasy campaign with RPG and tactical combat elements.',
      numberOfPlayers: '1-4',
      playingTime: '120-180 min',
      minAge: 14,
      weight: 3.9,
      designer: 'Isaac Childres',
      artist: 'Alexandr Elichev',
      comment: 'Ogromne pudło, setki godzin rozgrywki.',
    },
    {
      id: 'g13',
      name: 'Brass: Birmingham',
      shortDescription: 'Industrial England during the Industrial Revolution.',
      numberOfPlayers: '2-4',
      playingTime: '120 min',
      minAge: 14,
      weight: 3.9,
      designer: 'Gavan Brown, Matt Tolman, Martin Wallace',
      artist: 'Roxley',
      comment: 'Uważana za jedną z najlepszych gier ekonomicznych.',
    },
    {
      id: 'g14',
      name: 'Root',
      shortDescription: 'Asymmetric game about animals fighting for control over the forest.',
      numberOfPlayers: '2-4',
      playingTime: '60-90 min',
      minAge: 10,
      weight: 3.2,
      designer: 'Cole Wehrle',
      artist: 'Kyle Ferrin',
      comment: 'Kolorowa, ale wymagająca gra strategiczna.',
    },
    {
      id: 'g15',
      name: 'Blood Rage',
      shortDescription: 'Vikings fight for glory during Ragnarok.',
      numberOfPlayers: '2-4',
      playingTime: '60-90 min',
      minAge: 14,
      weight: 3.1,
      designer: 'Eric M. Lang',
      artist: 'Adrian Smith',
      comment: 'Dynamiczna gra area control z figurkami.',
    },
    {
      id: 'g16',
      name: 'Puerto Rico',
      shortDescription: 'Managing plantations and developing colonies in the New World.',
      numberOfPlayers: '3-5',
      playingTime: '90-150 min',
      minAge: 12,
      weight: 3.3,
      designer: 'Andreas Seyfarth',
      artist: 'Franz Vohwinkel',
      comment: 'Jeden z klasyków eurogier strategicznych.',
    },
    {
      id: 'g17',
      name: 'Agricola',
      shortDescription: 'Developing a farm and feeding your family in medieval times.',
      numberOfPlayers: '1-5',
      playingTime: '120 min',
      minAge: 12,
      weight: 3.6,
      designer: 'Uwe Rosenberg',
      artist: 'Klemens Franz',
      comment: 'Bardzo wymagająca gra ekonomiczna.',
    },
    {
      id: 'g18',
      name: 'Everdell',
      shortDescription: 'Building a fairy-tale city of forest animals.',
      numberOfPlayers: '1-4',
      playingTime: '40-80 min',
      minAge: 10,
      weight: 2.8,
      designer: 'James A. Wilson',
      artist: 'Andrew Bosley',
      comment: 'Przepiękne wykonanie i ciekawa mechanika kart.',
    },
    {
      id: 'g19',
      name: 'Codenames',
      shortDescription: 'Team game using word associations.',
      numberOfPlayers: '2-8',
      playingTime: '15-30 min',
      minAge: 14,
      weight: 1.5,
      designer: 'Vlaada Chvátil',
      artist: 'Tomáš Kučerovský',
      comment: 'Świetna na imprezy i większe spotkania.',
    },
    {
      id: 'g20',
      name: 'The Crew',
      shortDescription: 'Cooperative card game with space missions.',
      numberOfPlayers: '2-5',
      playingTime: '20 min',
      minAge: 10,
      weight: 2.0,
      designer: 'Thomas Sing',
      artist: 'Marco Armbruster',
      comment: 'Nowoczesna gra w stylu klasycznych karcianek.',
    },
    // g21 - g40
    {
      id: 'g21',
      name: "Tzolk'in: The Mayan Calendar",
      shortDescription: 'Economic game with rotating gears mechanism.',
      numberOfPlayers: '2-4',
      playingTime: '90 min',
      minAge: 12,
      weight: 3.6,
      designer: 'Simone Luciani, Daniele Tascini',
      artist: 'Dennis Lohausen',
      comment: 'Unikalny system planowania akcji na zębatkach.',
    },
    {
      id: 'g22',
      name: 'Concordia',
      shortDescription: 'Economic game about trade and expansion in Ancient Rome.',
      numberOfPlayers: '2-5',
      playingTime: '100 min',
      minAge: 12,
      weight: 3.0,
      designer: 'Mac Gerdts',
      artist: 'Marina Fahrenbach',
      comment: 'Elegancka mechanika i mało losowości.',
    },
    {
      id: 'g23',
      name: 'Lost Ruins of Arnak',
      shortDescription: 'Deck-building and worker placement with an archaeology theme.',
      numberOfPlayers: '1-4',
      playingTime: '60-120 min',
      minAge: 12,
      weight: 2.9,
      designer: 'Mín, Elwen',
      artist: 'Jiří Kůs',
      comment: 'Piękne wykonanie i świetne połączenie mechanik.',
    },
    {
      id: 'g24',
      name: 'Great Western Trail',
      shortDescription: 'Cattle transport through the Wild West.',
      numberOfPlayers: '2-4',
      playingTime: '75-150 min',
      minAge: 12,
      weight: 3.7,
      designer: 'Alexander Pfister',
      artist: 'Andreas Resch',
      comment: 'Strategiczna gra euro z dużą głębią.',
    },
    {
      id: 'g25',
      name: 'Pax Pamir: Second Edition',
      shortDescription: '19th-century politics and rivalry in Afghanistan.',
      numberOfPlayers: '1-5',
      playingTime: '60-120 min',
      minAge: 13,
      weight: 3.6,
      designer: 'Cole Wehrle',
      artist: 'Cole Wehrle',
      comment: 'Asymetryczna, polityczna rozgrywka z nietypową dynamiką.',
    },
    {
      id: 'g26',
      name: 'Viticulture',
      shortDescription: 'Managing a vineyard and wine production in Tuscany.',
      numberOfPlayers: '1-6',
      playingTime: '45-90 min',
      minAge: 13,
      weight: 2.9,
      designer: 'Jamey Stegmaier, Alan Stone',
      artist: 'Beth Sobel',
      comment: 'Przyjemna tematyka i zbalansowana ekonomia.',
    },
    {
      id: 'g27',
      name: 'Spirit Island',
      shortDescription: 'Cooperative defense of an island from colonizers.',
      numberOfPlayers: '1-4',
      playingTime: '90-120 min',
      minAge: 13,
      weight: 4.0,
      designer: 'R. Eric Reuss',
      artist: 'Jason Behnke',
      comment: 'Złożona, ale satysfakcjonująca kooperacja.',
    },
    {
      id: 'g29',
      name: 'Clank!: A Deck-Building Adventure',
      shortDescription: 'Deck-building with a dungeon adventure element.',
      numberOfPlayers: '2-4',
      playingTime: '30-60 min',
      minAge: 12,
      weight: 2.3,
      designer: 'Paul Dennen',
      artist: 'Randy Gallegos',
      comment: 'Exciting game with risk and reward.',
    },
    {
      id: 'g30',
      name: 'On Mars',
      shortDescription: 'Advanced game about colonizing Mars.',
      numberOfPlayers: '1-4',
      playingTime: '90-150 min',
      minAge: 14,
      weight: 4.6,
      designer: 'Vital Lacerda',
      artist: "Ian O'Toole",
      comment: 'One of the most demanding eurogames.',
    },
    {
      id: 'g31',
      name: 'Caverna: The Cave Farmers',
      shortDescription: 'Developing a farm and dwarf mines.',
      numberOfPlayers: '1-7',
      playingTime: '120 min',
      minAge: 12,
      weight: 3.8,
      designer: 'Uwe Rosenberg',
      artist: 'Klemens Franz',
      comment: 'An elaborate alternative to Agricola.',
    },
    {
      id: 'g32',
      name: 'Lisboa',
      shortDescription: 'Rebuilding Lisbon after the 1755 earthquake.',
      numberOfPlayers: '1-4',
      playingTime: '120-150 min',
      minAge: 12,
      weight: 4.6,
      designer: 'Vital Lacerda',
      artist: "Ian O'Toole",
      comment: 'A heavy eurogame with beautiful design.',
    },
    {
      id: 'g33',
      name: 'Cartographers',
      shortDescription: 'Drawing maps and scoring points in a roll & write style.',
      numberOfPlayers: '1-100',
      playingTime: '30-45 min',
      minAge: 10,
      weight: 1.9,
      designer: 'Jordy Adan',
      artist: 'Lucas Ribeiro',
      comment: 'Light and replayable drawing game.',
    },
    {
      id: 'g34',
      name: 'The Quacks of Quedlinburg',
      shortDescription: 'Building a bag of ingredients and creating potions.',
      numberOfPlayers: '2-4',
      playingTime: '45 min',
      minAge: 10,
      weight: 2.1,
      designer: 'Wolfgang Warsch',
      artist: 'Dennis Lohausen',
      comment: 'Great push-your-luck game with humor.',
    },
    {
      id: 'g35',
      name: 'Ark Nova',
      shortDescription: 'Building a modern zoo with attention to species conservation.',
      numberOfPlayers: '1-4',
      playingTime: '90-150 min',
      minAge: 14,
      weight: 3.7,
      designer: 'Mathias Wigge',
      artist: 'Loïc Billiau',
      comment: 'Combines euro mechanics with beautiful design.',
    },
    {
      id: 'g36',
      name: 'Paladins of the West Kingdom',
      shortDescription: 'Developing a medieval kingdom.',
      numberOfPlayers: '1-4',
      playingTime: '90-120 min',
      minAge: 12,
      weight: 3.6,
      designer: 'Shem Phillips, S J Macdonald',
      artist: 'Mihajlo Dimitrievski',
      comment: 'Challenging strategic game with card drafting.',
    },
    {
      id: 'g37',
      name: 'Patchwork',
      shortDescription: 'Competing in patching quilts from fabric pieces.',
      numberOfPlayers: '2',
      playingTime: '20-30 min',
      minAge: 8,
      weight: 1.6,
      designer: 'Uwe Rosenberg',
      artist: 'Klemens Franz',
      comment: 'Fast, enjoyable logic game for two players.',
    },
    {
      id: 'g38',
      name: 'Decrypto',
      shortDescription: 'Team game of encoding and guessing words.',
      numberOfPlayers: '3-8',
      playingTime: '30 min',
      minAge: 12,
      weight: 2.0,
      designer: 'Thomas Dagenais-Lespérance',
      artist: 'Fabien Fulchiron',
      comment: 'Great alternative to Codenames.',
    },
    {
      id: 'g39',
      name: 'Kingdomino',
      shortDescription: 'Building a kingdom from domino-style tiles.',
      numberOfPlayers: '2-4',
      playingTime: '15-20 min',
      minAge: 8,
      weight: 1.4,
      designer: 'Bruno Cathala',
      artist: 'Cyril Bouquet',
      comment: 'Simple and quick family game.',
    },
    {
      id: 'g40',
      name: 'Nemesis',
      shortDescription: 'Semi-cooperative survival game in an Alien-like setting.',
      numberOfPlayers: '1-5',
      playingTime: '120-180 min',
      minAge: 12,
      weight: 3.6,
      designer: 'Adam Kwapiński',
      artist: 'Ewa Labak',
      comment: 'Atmospheric and tense, strongly narrative-driven.',
    },
  ];

  getAllGames() {
    return this.dummy_games;
  }
  sortedGames(gameSearchValue: string) {
    return [...this.searchForGames(gameSearchValue)].sort((a, b) => a.name.localeCompare(b.name));
  }

  searchForGames(gameSearchValue: string) {
    const term = gameSearchValue.trim().toLowerCase();
    return this.dummy_games.filter((g) => (term ? g.name.toLowerCase().includes(term) : true));
  }

  selectedGame(selectedGameId: string): Game | undefined {
    return this.dummy_games.find((games) => games.id === selectedGameId);
  }
}
