export const dummy_games = [
  {
    id: 'g1',
    name: 'Catan',
    shortDescription: 'Kultowa gra ekonomiczna o osadnikach budujących swoje kolonie.',
    image: 'catan.jpg',
    numberOfPlayers: '3-4',
    playingTime: '60-90 min',
    minAge: 10,
    weight: 2.3,
    designer: 'Klaus Teuber',
    artist: 'Volkan Baga',
    comment: 'Świetna dla początkujących graczy, klasyk gatunku.',
  },
  {
    id: 'g2',
    name: 'Carcassonne',
    shortDescription: 'Budowanie średniowiecznych miast i dróg z kafelków.',
    image: 'carcassonne.jpg',
    numberOfPlayers: '2-5',
    playingTime: '30-45 min',
    minAge: 7,
    weight: 1.9,
    designer: 'Klaus-Jürgen Wrede',
    artist: 'Doris Matthäus',
    comment: 'Losowość kafelków daje dużo regrywalności.',
  },
  {
    id: 'g3',
    name: 'Ticket to Ride',
    shortDescription: 'Budowanie tras kolejowych na mapie świata.',
    image: 'ticket-to-ride.jpg',
    numberOfPlayers: '2-5',
    playingTime: '45-60 min',
    minAge: 8,
    weight: 1.8,
    designer: 'Alan R. Moon',
    artist: 'Julien Delval',
    comment: 'Łatwa do nauczenia, ale z fajną strategią.',
  },
  {
    id: 'g4',
    name: '7 Wonders',
    shortDescription: 'Rozwijaj swoją cywilizację przez trzy epoki.',
    image: '7-wonders.jpg',
    numberOfPlayers: '3-7',
    playingTime: '30 min',
    minAge: 10,
    weight: 2.3,
    designer: 'Antoine Bauza',
    artist: 'Miguel Coimbra',
    comment: 'Świetna w dużej grupie, szybka i dynamiczna.',
  },
  {
    id: 'g5',
    name: 'Splendor',
    shortDescription: 'Kolekcjonowanie klejnotów i rozwój renesansowych kupców.',
    image: 'splendor.jpg',
    numberOfPlayers: '2-4',
    playingTime: '30 min',
    minAge: 10,
    weight: 1.8,
    designer: 'Marc André',
    artist: 'Pascal Quidault',
    comment: 'Idealna gra wprowadzająca w planszówki.',
  },
  {
    id: 'g6',
    name: 'Dominion',
    shortDescription: 'Deck-building, w którym tworzysz własną talię kart.',
    image: 'dominion.jpg',
    numberOfPlayers: '2-4',
    playingTime: '30 min',
    minAge: 13,
    weight: 2.4,
    designer: 'Donald X. Vaccarino',
    artist: 'Matthias Catrein',
    comment: 'Pierwowzór gier typu deck-building.',
  },
  {
    id: 'g7',
    name: 'Pandemic',
    shortDescription: 'Kooperacyjna walka z rozprzestrzeniającymi się chorobami.',
    image: 'pandemic.jpg',
    numberOfPlayers: '2-4',
    playingTime: '45 min',
    minAge: 8,
    weight: 2.4,
    designer: 'Matt Leacock',
    artist: 'Josh Cappel',
    comment: 'Wciągająca gra kooperacyjna o ratowaniu świata.',
  },
  {
    id: 'g8',
    name: 'Azul',
    shortDescription: 'Układanie kolorowych płytek w portugalskim pałacu.',
    image: 'azul.jpg',
    numberOfPlayers: '2-4',
    playingTime: '30-45 min',
    minAge: 8,
    weight: 1.9,
    designer: 'Michael Kiesling',
    artist: 'Chris Quilliams',
    comment: 'Prosta zasady, ale dużo głębi w wyborach.',
  },
  {
    id: 'g9',
    name: 'Scythe',
    shortDescription: 'Alternatywna Europa 1920+ z mechami i frakcjami.',
    image: 'scythe.jpg',
    numberOfPlayers: '1-7',
    playingTime: '90-120 min',
    minAge: 14,
    weight: 3.4,
    designer: 'Jamey Stegmaier',
    artist: 'Jakub Różalski',
    comment: 'Piękna gra strategiczna z unikalnym klimatem.',
  },
  {
    id: 'g10',
    name: 'Terraforming Mars',
    shortDescription: 'Korporacje współpracują (i rywalizują) przy terraformowaniu Marsa.',
    image: 'terraforming-mars.jpg',
    numberOfPlayers: '1-5',
    playingTime: '120 min',
    minAge: 12,
    weight: 3.3,
    designer: 'Jacob Fryxelius',
    artist: 'Isaac Fryxelius',
    comment: 'Ogromna regrywalność i klimat naukowy.',
  },
  {
    id: 'g11',
    name: 'Wingspan',
    shortDescription: 'Kolekcjonowanie ptaków w rezerwacie przyrody.',
    image: 'wingspan.jpg',
    numberOfPlayers: '1-5',
    playingTime: '40-70 min',
    minAge: 10,
    weight: 2.4,
    designer: 'Elizabeth Hargrave',
    artist: 'Beth Sobel',
    comment: 'Piękne ilustracje i przyjemna mechanika.',
  },
  {
    id: 'g12',
    name: 'Gloomhaven',
    shortDescription: 'Epicka kampania fantasy z elementami RPG i walki taktycznej.',
    image: 'gloomhaven.jpg',
    numberOfPlayers: '1-4',
    playingTime: '120-180 min',
    minAge: 14,
    weight: 3.9,
    designer: 'Isaac Childres',
    artist: 'Alexandr Elichev',
    comment: 'Ogromne pudło, setki godzin rozgrywki.',
  },
  {
    id: 'g13',
    name: 'Brass: Birmingham',
    shortDescription: 'Przemysłowa Anglia w czasach rewolucji przemysłowej.',
    image: 'brass-birmingham.jpg',
    numberOfPlayers: '2-4',
    playingTime: '120 min',
    minAge: 14,
    weight: 3.9,
    designer: 'Gavan Brown, Matt Tolman, Martin Wallace',
    artist: 'Roxley',
    comment: 'Uważana za jedną z najlepszych gier ekonomicznych.',
  },
  {
    id: 'g14',
    name: 'Root',
    shortDescription: 'Asymetryczna gra o zwierzętach walczących o kontrolę nad lasem.',
    image: 'root.jpg',
    numberOfPlayers: '2-4',
    playingTime: '60-90 min',
    minAge: 10,
    weight: 3.2,
    designer: 'Cole Wehrle',
    artist: 'Kyle Ferrin',
    comment: 'Kolorowa, ale wymagająca gra strategiczna.',
  },
  {
    id: 'g15',
    name: 'Blood Rage',
    shortDescription: 'Wikingowie walczą o chwałę podczas Ragnaröku.',
    image: 'blood-rage.jpg',
    numberOfPlayers: '2-4',
    playingTime: '60-90 min',
    minAge: 14,
    weight: 3.1,
    designer: 'Eric M. Lang',
    artist: 'Adrian Smith',
    comment: 'Dynamiczna gra area control z figurkami.',
  },
  {
    id: 'g16',
    name: 'Puerto Rico',
    shortDescription: 'Zarządzanie plantacjami i rozwojem kolonii w Nowym Świecie.',
    image: 'puerto-rico.jpg',
    numberOfPlayers: '3-5',
    playingTime: '90-150 min',
    minAge: 12,
    weight: 3.3,
    designer: 'Andreas Seyfarth',
    artist: 'Franz Vohwinkel',
    comment: 'Jeden z klasyków eurogier strategicznych.',
  },
  {
    id: 'g17',
    name: 'Agricola',
    shortDescription: 'Rozwijanie farmy i karmienie rodziny w czasach średniowiecza.',
    image: 'agricola.jpg',
    numberOfPlayers: '1-5',
    playingTime: '120 min',
    minAge: 12,
    weight: 3.6,
    designer: 'Uwe Rosenberg',
    artist: 'Klemens Franz',
    comment: 'Bardzo wymagająca gra ekonomiczna.',
  },
  {
    id: 'g18',
    name: 'Everdell',
    shortDescription: 'Budowanie bajkowego miasta zwierząt leśnych.',
    image: 'everdell.jpg',
    numberOfPlayers: '1-4',
    playingTime: '40-80 min',
    minAge: 10,
    weight: 2.8,
    designer: 'James A. Wilson',
    artist: 'Andrew Bosley',
    comment: 'Przepiękne wykonanie i ciekawa mechanika kart.',
  },
  {
    id: 'g19',
    name: 'Codenames',
    shortDescription: 'Gra drużynowa w skojarzenia słowne.',
    image: 'codenames.jpg',
    numberOfPlayers: '2-8',
    playingTime: '15-30 min',
    minAge: 14,
    weight: 1.5,
    designer: 'Vlaada Chvátil',
    artist: 'Tomáš Kučerovský',
    comment: 'Świetna na imprezy i większe spotkania.',
  },
  {
    id: 'g20',
    name: 'The Crew',
    shortDescription: 'Kooperacyjna gra karciana z misjami w kosmosie.',
    image: 'the-crew.jpg',
    numberOfPlayers: '2-5',
    playingTime: '20 min',
    minAge: 10,
    weight: 2.0,
    designer: 'Thomas Sing',
    artist: 'Marco Armbruster',
    comment: 'Nowoczesna gra w stylu klasycznych karcianek.',
  },
  {
    id: 'g21',
    name: "Tzolk'in: The Mayan Calendar",
    shortDescription: 'Gra ekonomiczna z mechanizmem obrotowych kół zębatych.',
    image: 'tzolkin.jpg',
    numberOfPlayers: '2–4',
    playingTime: '90 min',
    minAge: 12,
    weight: 3.6,
    designer: 'Simone Luciani, Daniele Tascini',
    artist: 'Dennis Lohausen',
    comment: 'Unikalny system planowania akcji na zębatkach.',
  },
  {
    id: 'g22',
    name: 'Concordia',
    shortDescription: 'Ekonomiczna gra o handlu i ekspansji w starożytnym Rzymie.',
    image: 'concordia.jpg',
    numberOfPlayers: '2–5',
    playingTime: '100 min',
    minAge: 12,
    weight: 3.0,
    designer: 'Mac Gerdts',
    artist: 'Marina Fahrenbach',
    comment: 'Elegancka mechanika i mało losowości.',
  },
  {
    id: 'g23',
    name: 'Lost Ruins of Arnak',
    shortDescription: 'Deck-building i worker placement w klimacie archeologii.',
    image: 'lost-ruins-of-arnak.jpg',
    numberOfPlayers: '1–4',
    playingTime: '60–120 min',
    minAge: 12,
    weight: 2.9,
    designer: 'Mín, Elwen',
    artist: 'Jiří Kůs',
    comment: 'Piękne wykonanie i świetne połączenie mechanik.',
  },
  {
    id: 'g24',
    name: 'Great Western Trail',
    shortDescription: 'Transport bydła przez Dziki Zachód.',
    image: 'great-western-trail.jpg',
    numberOfPlayers: '2–4',
    playingTime: '75–150 min',
    minAge: 12,
    weight: 3.7,
    designer: 'Alexander Pfister',
    artist: 'Andreas Resch',
    comment: 'Strategiczna gra euro z dużą głębią.',
  },
  {
    id: 'g25',
    name: 'Pax Pamir: Second Edition',
    shortDescription: 'XIX-wieczna polityka i rywalizacja w Afganistanie.',
    image: 'pax-pamir.jpg',
    numberOfPlayers: '1–5',
    playingTime: '60–120 min',
    minAge: 13,
    weight: 3.6,
    designer: 'Cole Wehrle',
    artist: 'Cole Wehrle',
    comment: 'Asymetryczna, polityczna rozgrywka z nietypową dynamiką.',
  },
  {
    id: 'g26',
    name: 'Viticulture',
    shortDescription: 'Zarządzanie winnicą i produkcja wina w Toskanii.',
    image: 'viticulture.jpg',
    numberOfPlayers: '1–6',
    playingTime: '45–90 min',
    minAge: 13,
    weight: 2.9,
    designer: 'Jamey Stegmaier, Alan Stone',
    artist: 'Beth Sobel',
    comment: 'Przyjemna tematyka i zbalansowana ekonomia.',
  },
  {
    id: 'g27',
    name: 'Spirit Island',
    shortDescription: 'Kooperacyjna obrona wyspy przed kolonizatorami.',
    image: 'spirit-island.jpg',
    numberOfPlayers: '1–4',
    playingTime: '90–120 min',
    minAge: 13,
    weight: 4.0,
    designer: 'R. Eric Reuss',
    artist: 'Jason Behnke',
    comment: 'Złożona, ale satysfakcjonująca kooperacja.',
  },
  {
    id: 'g28',
    name: 'Obsession',
    shortDescription: 'Zarządzanie wiktoriańskim majątkiem i relacjami towarzyskimi.',
    image: 'obsession.jpg',
    numberOfPlayers: '1–4',
    playingTime: '30–90 min',
    minAge: 14,
    weight: 3.2,
    designer: 'Dan Hallagan',
    artist: 'Dan Hallagan',
    comment: 'Klimat rodem z „Dumy i Uprzedzenia”.',
  },
  {
    id: 'g29',
    name: 'Clank!: A Deck-Building Adventure',
    shortDescription: 'Deck-building z elementem przygody w lochach.',
    image: 'clank.jpg',
    numberOfPlayers: '2–4',
    playingTime: '30–60 min',
    minAge: 12,
    weight: 2.3,
    designer: 'Paul Dennen',
    artist: 'Randy Gallegos',
    comment: 'Ekscytująca gra z ryzykiem i nagrodą.',
  },
  {
    id: 'g30',
    name: 'On Mars',
    shortDescription: 'Zaawansowana gra o kolonizacji Marsa.',
    image: 'on-mars.jpg',
    numberOfPlayers: '1–4',
    playingTime: '90–150 min',
    minAge: 14,
    weight: 4.6,
    designer: 'Vital Lacerda',
    artist: "Ian O'Toole",
    comment: 'Jedna z najbardziej wymagających eurogier.',
  },
  {
    id: 'g31',
    name: 'Caverna: The Cave Farmers',
    shortDescription: 'Rozwijanie gospodarstwa i kopalni krasnoludów.',
    image: 'caverna.jpg',
    numberOfPlayers: '1–7',
    playingTime: '120 min',
    minAge: 12,
    weight: 3.8,
    designer: 'Uwe Rosenberg',
    artist: 'Klemens Franz',
    comment: 'Rozbudowana alternatywa dla Agricoli.',
  },
  {
    id: 'g32',
    name: 'Lisboa',
    shortDescription: 'Odbudowa Lizbony po trzęsieniu ziemi w 1755 roku.',
    image: 'lisboa.jpg',
    numberOfPlayers: '1–4',
    playingTime: '120–150 min',
    minAge: 12,
    weight: 4.6,
    designer: 'Vital Lacerda',
    artist: "Ian O'Toole",
    comment: 'Ciężkie euro z przepiękną oprawą.',
  },
  {
    id: 'g33',
    name: 'Cartographers',
    shortDescription: 'Rysowanie mapy i zdobywanie punktów w trybie roll & write.',
    image: 'cartographers.jpg',
    numberOfPlayers: '1–100',
    playingTime: '30–45 min',
    minAge: 10,
    weight: 1.9,
    designer: 'Jordy Adan',
    artist: 'Lucas Ribeiro',
    comment: 'Lekka i regrywalna gra do rysowania.',
  },
  {
    id: 'g34',
    name: 'The Quacks of Quedlinburg',
    shortDescription: 'Budowanie woreczka składników i tworzenie mikstur.',
    image: 'quacks.jpg',
    numberOfPlayers: '2–4',
    playingTime: '45 min',
    minAge: 10,
    weight: 2.1,
    designer: 'Wolfgang Warsch',
    artist: 'Dennis Lohausen',
    comment: 'Świetna gra push-your-luck z humorem.',
  },
  {
    id: 'g35',
    name: 'Ark Nova',
    shortDescription: 'Budowanie nowoczesnego zoo z dbałością o ochronę gatunków.',
    image: 'ark-nova.jpg',
    numberOfPlayers: '1–4',
    playingTime: '90–150 min',
    minAge: 14,
    weight: 3.7,
    designer: 'Mathias Wigge',
    artist: 'Loïc Billiau',
    comment: 'Łączy mechaniki euro z piękną oprawą.',
  },
  {
    id: 'g36',
    name: 'Paladins of the West Kingdom',
    shortDescription: 'Rozwijanie królestwa w średniowieczu.',
    image: 'paladins.jpg',
    numberOfPlayers: '1–4',
    playingTime: '90–120 min',
    minAge: 12,
    weight: 3.6,
    designer: 'Shem Phillips, S J Macdonald',
    artist: 'Mihajlo Dimitrievski',
    comment: 'Wymagająca gra strategiczna z draftem kart.',
  },
  {
    id: 'g37',
    name: 'Patchwork',
    shortDescription: 'Rywalizacja w układaniu koców z kawałków materiału.',
    image: 'patchwork.jpg',
    numberOfPlayers: '2',
    playingTime: '20–30 min',
    minAge: 8,
    weight: 1.6,
    designer: 'Uwe Rosenberg',
    artist: 'Klemens Franz',
    comment: 'Szybka, przyjemna gra logiczna dla dwóch osób.',
  },
  {
    id: 'g38',
    name: 'Decrypto',
    shortDescription: 'Gra drużynowa w kodowanie i odgadywanie haseł.',
    image: 'decrypto.jpg',
    numberOfPlayers: '3–8',
    playingTime: '30 min',
    minAge: 12,
    weight: 2.0,
    designer: 'Thomas Dagenais-Lespérance',
    artist: 'Fabien Fulchiron',
    comment: 'Świetna alternatywa dla Codenames.',
  },
  {
    id: 'g39',
    name: 'Kingdomino',
    shortDescription: 'Budowanie królestwa z kafelków w stylu domina.',
    image: 'kingdomino.jpg',
    numberOfPlayers: '2–4',
    playingTime: '15–20 min',
    minAge: 8,
    weight: 1.4,
    designer: 'Bruno Cathala',
    artist: 'Cyril Bouquet',
    comment: 'Prosta i szybka gra rodzinna.',
  },
  {
    id: 'g40',
    name: 'Nemesis',
    shortDescription: 'Półkooperacyjna gra survivalowa w klimacie Obcego.',
    image: 'nemesis.jpg',
    numberOfPlayers: '1–5',
    playingTime: '120–180 min',
    minAge: 12,
    weight: 3.6,
    designer: 'Adam Kwapiński',
    artist: 'Ewa Labak',
    comment: 'Pełna klimatu i napięcia, mocno narracyjna.',
  },
];
